#### Cannibals of Morrowind Updated (https://www.nexusmods.com/morrowind/mods/47358)
# Body parts and skulls this mod adds to NPC and creature inventories.
# Listed here so surrendering actors don't dump them on the ground.

item_dump_disable:
  recordIds:
    - MOR_apparatus_khajiitskull
    - MOR_apparatus_orcskull
    - MOR_apparatus_argoskull
    - MOR_apparatus_vampskull
    - MOR_khajiit_ear
    - MOR_apparatus_nordskull
    - MOR_apparatus_bretonskull
    - MOR_apparatus_imperialskull
    - MOR_apparatus_redguardskull
    - MOR_apparatus_altskull
    - MOR_apparatus_bosskull
    - MOR_apparatus_dunskull
    - MOR_nord_brain
    - MOR_orc_brain
    - MOR_arg_brain
    - MOR_altmer_brain
    - MOR_breton_brain
    - MOR_bosmer_brain
    - MOR_dunmer_brain
    - MOR_imperial_brain
    - MOR_khajiit_brain
    - MOR_redguard_brain
    - MOR_altmer_heart
    - MOR_argo_heart
    - MOR_bosmer_heart
    - MOR_breton_heart
    - MOR_dunmer_heart
    - MOR_imperial_heart
    - MOR_khajiit_heart
    - MOR_nord_heart
    - MOR_orc_heart
    - MOR_redguard_heart
    - MOR_altmer_eye
    - MOR_argo_eye
    - MOR_bosmer_eye
    - MOR_breton_eye
    - MOR_dunmer_eye
    - MOR_imperial_eye
    - MOR_khajiit_eye
    - MOR_orc_eye
    - MOR_redguard_eye
    - MOR_altmer_flesh
    - MOR_argo_flesh
    - MOR_bosmer_flesh
    - MOR_breton_flesh
    - MOR_dunmer_flesh
    - MOR_Imperial_flesh
    - MOR_khajiit_flesh
    - MOR_nord_flesh
    - MOR_orc_flesh
    - MOR_redguard_flesh
    - MOR_argo_tail
    - MOR_imperial_tongue
    - MOR_nord_bones
    - MOR_intestine
    - MOR_apparatus_vivskull
    - MOR_apparatus_fargothskull
    - MOR_apparatus_divaythskull
    - MOR_apparatus_dukeskull
    - MOR_apparatus_gothren
    - MOR_apparatus_orvasskull
    - MOR_apparatus_aundaeskull
    - MOR_apparatus_berneskull
    - MOR_apparatus_quarraskull
    - MOR_apparatus_dbskull
    - MOR_apparatus_lalatiaskull
    - MOR_apparatus_varusskull
    - MOR_apparatus_trebskull
    - MOR_apparatus_enoskull
    - MOR_apparatus_saryoniskull
    - MOR_apparatus_jimskull
    - aa_skull_sleeper
    - aa_skull_ashghoul
    - aa_skull_ashvamp
